const poemData = [
    { text: "某", py: "mǒu", zh: "某个人，这里指故事中的主人公（某人）。", en: "A certain person" },
    { text: "恶鼠", py: "wù shǔ", zh: "讨厌老鼠，痛恨老鼠。“恶”，动词，讨厌、痛恨。", en: "hated rats,", exam: true },
    { text: "，", punc: true },
    { text: "破家", py: "pò jiā", zh: "不惜倾尽家财，花费重金。", en: "and spent a fortune", exam: true },
    { text: "求", py: "qiú", zh: "寻找，寻求。", en: "to look for" },
    { text: "良猫", py: "liáng māo", zh: "优秀的猫，捕鼠能手。", en: "a good cat." },
    { text: "。", punc: true },
    { text: "厌", py: "yàn", zh: "动词，饱食，让……吃饱（古汉语中同“餍”）。", en: "He fed it to its heart's content", exam: true },
    { text: "以", py: "yǐ", zh: "介词，用。", en: "with" },
    { text: "腥膏", py: "xīng gāo", zh: "鱼鲜和肥肉（美味的肉食）。", en: "fish and fat meat," },
    { text: "，", punc: true },
    { text: "眠", py: "mián", zh: "动词，让……睡觉，安置。", en: "and let it sleep" },
    { text: "以", py: "yǐ", zh: "介词，用。", en: "on" },
    { text: "毡罽", py: "zhān jì", zh: "毛毡和毯子（温暖舒适的垫子，后字读 jì）。", en: "soft rugs and carpets.", exam: true },
    { text: "。", punc: true },
    { text: "猫", py: "māo", zh: "猫。", en: "The cat," },
    { text: "既", py: "jì", zh: "连词，已经，在……之后。", en: "having become", exam: true },
    { text: "饱", py: "bǎo", zh: "吃饱。", en: "both full" },
    { text: "且", py: "qiě", zh: "连词，并且，而且。", en: "and" },
    { text: "安", py: "ān", zh: "安逸，舒适。", en: "comfortable," },
    { text: "，", punc: true },
    { text: "率", py: "shuài", zh: "副词，基本上，大都，往往。", en: "generally", exam: true },
    { text: "不", py: "bù", zh: "不。", en: "did not" },
    { text: "捕鼠", py: "bǔ shǔ", zh: "捕捉老鼠。", en: "catch any rats." },
    { text: "区域", punc: true },
    { text: "甚者", py: "shèn zhě", zh: "更严重的（情况）。“甚”，厉害、严重。", en: "Worse still,", exam: true },
    { text: "与", py: "yǔ", zh: "介词，和，跟。", en: "it even" },
    { text: "鼠", py: "shǔ", zh: "老鼠。", en: "with the rats" },
    { text: "游戏", py: "yóu xì", zh: "玩耍，嬉戏。", en: "played games," },
    { text: "，", punc: true },
    { text: "鼠", py: "shǔ", zh: "老鼠们。", en: "and the rats" },
    { text: "以故", py: "yǐ gù", zh: "因此，因为这个缘故（特殊因果词组）。", en: "because of this", exam: true },
    { text: "益暴", py: "yì bào", zh: "更加凶暴，更加猖獗。“益”，更加；“暴”，凶残猖獗。", en: "became even more rampant.", exam: true },
    { text: "。", punc: true },
    { text: "某", py: "mǒu", zh: "某人（主人）。", en: "The man" },
    { text: "怒", py: "nù", zh: "非常生气。", en: "grew furious," },
    { text: "，", punc: true },
    { text: "遂", py: "suì", zh: "副词，于是，就。", en: "and consequently", exam: true },
    { text: "不复", py: "bù fù", zh: "不再，再也不（复，再）。", en: "no longer" },
    { text: "蓄猫", py: "xù māo", zh: "养猫。“蓄”，喂养。", en: "kept cats," },
    { text: "，", punc: true },
    { text: "以为", py: "yǐ wéi", zh: "动词，认为（主观断定）。", en: "believing that" },
    { text: "天下", py: "tiān xià", zh: "世界上，普天之下。", en: "in the world" },
    { text: "无", py: "wú", zh: "没有。", en: "there were no" },
    { text: "良猫", py: "liáng māo", zh: "好猫。", en: "good cats at all." },
    { text: "也", py: "yě", zh: "了（语气助词，表判断定论）。", en: "(particle)" },
    { text: "。", punc: true }
];
